services:
  zipkin:
    image: 'ghcr.io/openzipkin-contrib/zipkin-otel:latest'
    ports:
    - '9411:4318'
    - '4317' # dummy
    environment:
      UI_ENABLED: 'true'
      QUERY_PORT: '4318'
    labels:
      org.springframework.boot.service-connection: 'otel/opentelemetry-collector-contrib'
      org.springframework.boot.readiness-check.tcp.disable: true