name: Todo Frontend Webflux CI
on:
  push:
    branches:
    - main
    paths:
    - todo-frontend-webflux/src/**
    - todo-frontend/ui/**
    - todo-frontend-webflux/pom.xml
    - .github/workflows/*
  pull_request:
    branches:
    - main
    paths:
    - todo-frontend-webflux/src/**
    - todo-frontend/ui/**
    - todo-frontend-webflux/pom.xml
    - .github/workflows/*
jobs:
  unit-test:
    uses: categolj/workflows/.github/workflows/unit-test.yaml@main
    with:
      pom_dir: todo-frontend-webflux
  build-oci-image-jvm-amd64:
    needs: unit-test
    uses: categolj/workflows/.github/workflows/build-oci-image-jvm.yaml@main
    with:
      pom_dir: todo-frontend-webflux
      image_name: jvm_amd64
      image_file: jvm_amd64.yaml
      runs_on: ubuntu-latest
  build-oci-image-jvm-aarch64:
    needs: unit-test
    uses: categolj/workflows/.github/workflows/build-oci-image-jvm.yaml@main
    with:
      pom_dir: todo-frontend-webflux
      image_name: jvm_aarch64
      image_file: jvm_aarch64.yaml
      runs_on: ubuntu-24.04-arm
  push-multi-arch-image-jvm:
    needs:
    - build-oci-image-jvm-amd64
    - build-oci-image-jvm-aarch64
    uses: categolj/workflows/.github/workflows/push-multi-arch-image.yaml@main
    with:
      pom_dir: todo-frontend-webflux
      prefix: jvm
  save-image-jvm-amd64:
    needs: build-oci-image-jvm-amd64
    uses: categolj/workflows/.github/workflows/save-images.yaml@main
    with:
      image_name: jvm_amd64
      image_file: jvm_amd64.yaml
  save-image-jvm-aarch64:
    needs: build-oci-image-jvm-aarch64
    uses: categolj/workflows/.github/workflows/save-images.yaml@main
    with:
      image_name: jvm_aarch64
      image_file: jvm_aarch64.yaml